// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.17.1
// source: protos/person.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Person_EyeColor int32

const (
	Person_UNKNOWN Person_EyeColor = 0
	Person_GREEN   Person_EyeColor = 1
	Person_BLUE    Person_EyeColor = 2
	Person_BROWN   Person_EyeColor = 3
)

// Enum value maps for Person_EyeColor.
var (
	Person_EyeColor_name = map[int32]string{
		0: "UNKNOWN",
		1: "GREEN",
		2: "BLUE",
		3: "BROWN",
	}
	Person_EyeColor_value = map[string]int32{
		"UNKNOWN": 0,
		"GREEN":   1,
		"BLUE":    2,
		"BROWN":   3,
	}
)

func (x Person_EyeColor) Enum() *Person_EyeColor {
	p := new(Person_EyeColor)
	*p = x
	return p
}

func (x Person_EyeColor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Person_EyeColor) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_person_proto_enumTypes[0].Descriptor()
}

func (Person_EyeColor) Type() protoreflect.EnumType {
	return &file_protos_person_proto_enumTypes[0]
}

func (x Person_EyeColor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Person_EyeColor.Descriptor instead.
func (Person_EyeColor) EnumDescriptor() ([]byte, []int) {
	return file_protos_person_proto_rawDescGZIP(), []int{0, 0}
}

type DayOfWeek_Day int32

const (
	DayOfWeek_UNDEFINED DayOfWeek_Day = 0
	DayOfWeek_MONDAY    DayOfWeek_Day = 1
	DayOfWeek_TUESDAY   DayOfWeek_Day = 2
	DayOfWeek_WEDNESDAY DayOfWeek_Day = 3
	DayOfWeek_THURSDAY  DayOfWeek_Day = 4
	DayOfWeek_FRIDAY    DayOfWeek_Day = 5
	DayOfWeek_SATURDAY  DayOfWeek_Day = 6
	DayOfWeek_SUNDAY    DayOfWeek_Day = 7
)

// Enum value maps for DayOfWeek_Day.
var (
	DayOfWeek_Day_name = map[int32]string{
		0: "UNDEFINED",
		1: "MONDAY",
		2: "TUESDAY",
		3: "WEDNESDAY",
		4: "THURSDAY",
		5: "FRIDAY",
		6: "SATURDAY",
		7: "SUNDAY",
	}
	DayOfWeek_Day_value = map[string]int32{
		"UNDEFINED": 0,
		"MONDAY":    1,
		"TUESDAY":   2,
		"WEDNESDAY": 3,
		"THURSDAY":  4,
		"FRIDAY":    5,
		"SATURDAY":  6,
		"SUNDAY":    7,
	}
)

func (x DayOfWeek_Day) Enum() *DayOfWeek_Day {
	p := new(DayOfWeek_Day)
	*p = x
	return p
}

func (x DayOfWeek_Day) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DayOfWeek_Day) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_person_proto_enumTypes[1].Descriptor()
}

func (DayOfWeek_Day) Type() protoreflect.EnumType {
	return &file_protos_person_proto_enumTypes[1]
}

func (x DayOfWeek_Day) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DayOfWeek_Day.Descriptor instead.
func (DayOfWeek_Day) EnumDescriptor() ([]byte, []int) {
	return file_protos_person_proto_rawDescGZIP(), []int{3, 0}
}

type Person struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Age             int32           `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	FirstName       string          `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName        string          `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Picture         []byte          `protobuf:"bytes,4,opt,name=picture,proto3" json:"picture,omitempty"` // Image in .jpeg format
	ProfileVerified bool            `protobuf:"varint,5,opt,name=profile_verified,json=profileVerified,proto3" json:"profile_verified,omitempty"`
	Height          float32         `protobuf:"fixed32,6,opt,name=height,proto3" json:"height,omitempty"`
	PhoneNumbers    []string        `protobuf:"bytes,7,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	EyeColor        Person_EyeColor `protobuf:"varint,8,opt,name=eye_color,json=eyeColor,proto3,enum=person.Person_EyeColor" json:"eye_color,omitempty"`
	BirthdayDate    *Date           `protobuf:"bytes,9,opt,name=birthday_date,json=birthdayDate,proto3" json:"birthday_date,omitempty"`
}

func (x *Person) Reset() {
	*x = Person{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_person_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_protos_person_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_protos_person_proto_rawDescGZIP(), []int{0}
}

func (x *Person) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Person) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Person) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Person) GetPicture() []byte {
	if x != nil {
		return x.Picture
	}
	return nil
}

func (x *Person) GetProfileVerified() bool {
	if x != nil {
		return x.ProfileVerified
	}
	return false
}

func (x *Person) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Person) GetPhoneNumbers() []string {
	if x != nil {
		return x.PhoneNumbers
	}
	return nil
}

func (x *Person) GetEyeColor() Person_EyeColor {
	if x != nil {
		return x.EyeColor
	}
	return Person_UNKNOWN
}

func (x *Person) GetBirthdayDate() *Date {
	if x != nil {
		return x.BirthdayDate
	}
	return nil
}

type LatitudeLongitude struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float32 `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float32 `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *LatitudeLongitude) Reset() {
	*x = LatitudeLongitude{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_person_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LatitudeLongitude) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatitudeLongitude) ProtoMessage() {}

func (x *LatitudeLongitude) ProtoReflect() protoreflect.Message {
	mi := &file_protos_person_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatitudeLongitude.ProtoReflect.Descriptor instead.
func (*LatitudeLongitude) Descriptor() ([]byte, []int) {
	return file_protos_person_proto_rawDescGZIP(), []int{1}
}

func (x *LatitudeLongitude) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LatitudeLongitude) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type Money struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrencyCode   string `protobuf:"bytes,1,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	IntegralAmount int32  `protobuf:"varint,2,opt,name=integral_amount,json=integralAmount,proto3" json:"integral_amount,omitempty"`
	DecimalAmount  int32  `protobuf:"varint,3,opt,name=decimal_amount,json=decimalAmount,proto3" json:"decimal_amount,omitempty"`
}

func (x *Money) Reset() {
	*x = Money{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_person_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_protos_person_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_protos_person_proto_rawDescGZIP(), []int{2}
}

func (x *Money) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *Money) GetIntegralAmount() int32 {
	if x != nil {
		return x.IntegralAmount
	}
	return 0
}

func (x *Money) GetDecimalAmount() int32 {
	if x != nil {
		return x.DecimalAmount
	}
	return 0
}

type DayOfWeek struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day DayOfWeek_Day `protobuf:"varint,1,opt,name=day,proto3,enum=person.DayOfWeek_Day" json:"day,omitempty"`
}

func (x *DayOfWeek) Reset() {
	*x = DayOfWeek{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_person_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DayOfWeek) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayOfWeek) ProtoMessage() {}

func (x *DayOfWeek) ProtoReflect() protoreflect.Message {
	mi := &file_protos_person_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayOfWeek.ProtoReflect.Descriptor instead.
func (*DayOfWeek) Descriptor() ([]byte, []int) {
	return file_protos_person_proto_rawDescGZIP(), []int{3}
}

func (x *DayOfWeek) GetDay() DayOfWeek_Day {
	if x != nil {
		return x.Day
	}
	return DayOfWeek_UNDEFINED
}

type PersonExercise struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName   string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	MiddleNames []string `protobuf:"bytes,2,rep,name=middle_names,json=middleNames,proto3" json:"middle_names,omitempty"`
	LastName    string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
}

func (x *PersonExercise) Reset() {
	*x = PersonExercise{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_person_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonExercise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonExercise) ProtoMessage() {}

func (x *PersonExercise) ProtoReflect() protoreflect.Message {
	mi := &file_protos_person_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonExercise.ProtoReflect.Descriptor instead.
func (*PersonExercise) Descriptor() ([]byte, []int) {
	return file_protos_person_proto_rawDescGZIP(), []int{4}
}

func (x *PersonExercise) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *PersonExercise) GetMiddleNames() []string {
	if x != nil {
		return x.MiddleNames
	}
	return nil
}

func (x *PersonExercise) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

var File_protos_person_proto protoreflect.FileDescriptor

var file_protos_person_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x1a, 0x11, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xf8, 0x02, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x69, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x69, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x76,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x34, 0x0a, 0x09, 0x65,
	0x79, 0x65, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17,
	0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x45,
	0x79, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x08, 0x65, 0x79, 0x65, 0x43, 0x6f, 0x6c, 0x6f,
	0x72, 0x12, 0x2f, 0x0a, 0x0d, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x5f, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x64, 0x61, 0x74, 0x65, 0x2e,
	0x44, 0x61, 0x74, 0x65, 0x52, 0x0c, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x44, 0x61,
	0x74, 0x65, 0x22, 0x37, 0x0a, 0x08, 0x45, 0x79, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x47,
	0x52, 0x45, 0x45, 0x4e, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4c, 0x55, 0x45, 0x10, 0x02,
	0x12, 0x09, 0x0a, 0x05, 0x42, 0x52, 0x4f, 0x57, 0x4e, 0x10, 0x03, 0x22, 0x4d, 0x0a, 0x11, 0x4c,
	0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x7c, 0x0a, 0x05, 0x4d, 0x6f,
	0x6e, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x6e, 0x74, 0x65,
	0x67, 0x72, 0x61, 0x6c, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x5f, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x64, 0x65, 0x63, 0x69, 0x6d,
	0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xa6, 0x01, 0x0a, 0x09, 0x44, 0x61, 0x79,
	0x4f, 0x66, 0x57, 0x65, 0x65, 0x6b, 0x12, 0x27, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x44, 0x61, 0x79,
	0x4f, 0x66, 0x57, 0x65, 0x65, 0x6b, 0x2e, 0x44, 0x61, 0x79, 0x52, 0x03, 0x64, 0x61, 0x79, 0x22,
	0x70, 0x0a, 0x03, 0x44, 0x61, 0x79, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49,
	0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x4f, 0x4e, 0x44, 0x41, 0x59, 0x10,
	0x01, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x55, 0x45, 0x53, 0x44, 0x41, 0x59, 0x10, 0x02, 0x12, 0x0d,
	0x0a, 0x09, 0x57, 0x45, 0x44, 0x4e, 0x45, 0x53, 0x44, 0x41, 0x59, 0x10, 0x03, 0x12, 0x0c, 0x0a,
	0x08, 0x54, 0x48, 0x55, 0x52, 0x53, 0x44, 0x41, 0x59, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x46,
	0x52, 0x49, 0x44, 0x41, 0x59, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x41, 0x54, 0x55, 0x52,
	0x44, 0x41, 0x59, 0x10, 0x06, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x55, 0x4e, 0x44, 0x41, 0x59, 0x10,
	0x07, 0x22, 0x6f, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x45, 0x78, 0x65, 0x72, 0x63,
	0x69, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_person_proto_rawDescOnce sync.Once
	file_protos_person_proto_rawDescData = file_protos_person_proto_rawDesc
)

func file_protos_person_proto_rawDescGZIP() []byte {
	file_protos_person_proto_rawDescOnce.Do(func() {
		file_protos_person_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_person_proto_rawDescData)
	})
	return file_protos_person_proto_rawDescData
}

var file_protos_person_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protos_person_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_person_proto_goTypes = []interface{}{
	(Person_EyeColor)(0),      // 0: person.Person.EyeColor
	(DayOfWeek_Day)(0),        // 1: person.DayOfWeek.Day
	(*Person)(nil),            // 2: person.Person
	(*LatitudeLongitude)(nil), // 3: person.LatitudeLongitude
	(*Money)(nil),             // 4: person.Money
	(*DayOfWeek)(nil),         // 5: person.DayOfWeek
	(*PersonExercise)(nil),    // 6: person.PersonExercise
	(*Date)(nil),              // 7: date.Date
}
var file_protos_person_proto_depIdxs = []int32{
	0, // 0: person.Person.eye_color:type_name -> person.Person.EyeColor
	7, // 1: person.Person.birthday_date:type_name -> date.Date
	1, // 2: person.DayOfWeek.day:type_name -> person.DayOfWeek.Day
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_person_proto_init() }
func file_protos_person_proto_init() {
	if File_protos_person_proto != nil {
		return
	}
	file_protos_date_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protos_person_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_person_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LatitudeLongitude); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_person_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Money); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_person_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DayOfWeek); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_person_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonExercise); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_person_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_person_proto_goTypes,
		DependencyIndexes: file_protos_person_proto_depIdxs,
		EnumInfos:         file_protos_person_proto_enumTypes,
		MessageInfos:      file_protos_person_proto_msgTypes,
	}.Build()
	File_protos_person_proto = out.File
	file_protos_person_proto_rawDesc = nil
	file_protos_person_proto_goTypes = nil
	file_protos_person_proto_depIdxs = nil
}
